propel:
  product:
    _attributes: { phpName: product }
    id: { type: integer, autoIncrement: true, required: true, size: 11, primaryString: true }
    name: { type: varchar, size: 255 }
    price: { type: double }
    quantity: { type: integer }
    image: { type: longvarchar }
